### PR TITLE
removing the dependency on ninject and adding separate ico nuget packages

### PR DESCRIPTION
**Pull request by ribsdigital**
this is a very tentative pull request as i appreciate that gibe use ninject and the library is predominantly for internal use...

however, i've now used the library on several projects as it's the best solution to the problem of js and css caching i've found so far ;)

the main thing is the dependency on ninject as each of the projects i've been working on has used a different ioc container...

in addition, the original 'DefaultNinjectBindingsModule.cs' doesn't contain the bindings for the 'Gibe.FileSystem' interfaces required to get the cache busting package working.

so i wondered if removing the ninject dependency and creating additional packages per ioc container might be viable?

i appreciate that this is a bit more work in terms of the nuget packages creation but it does solve the issue of the ninject dependency and follows the pattern established by many other projects e.g. having a core package and then sub packages to cover additional features.

thought i'd throw it out there as an idea?!

### CODE REVIEW

**Comment by stevetemple** [comment]
Nice, I wanted to OSS this for a while but the dependencies you've mentioned are the issue. I feel I could have the dependencies self managed in the module itself would be the way to go without any IoC or DI framework and without any Gibe.XXX dependencies. Essentially making it entirely self contained

**Comment by ribsdigital** [comment]
i reckon it'd be easy enough to move the code called from the 'Gibe.FileSystem' package into the project, there's 2 interfaces but only 3 items being used:

**IPaths**
ServerMapPath

**IFileService**
FileExists
ReadAllText

> ...could have the dependencies self managed in the module itself would be the way to go...

are you thinking removing the interfaces or keep them and instance in constructors? the later would mean unit testing is possible (although there's not tests currently in the project...).

tbh i only just noticed that there's two implementations of the 'IManifestFileFactory' interface!

HardcodedManifestFileFactory
ConfigManifestFileFactory

i've only used **ConfigManifestFileFactory** in the projects i've worked with but it looks like the **HardcodedManifestFileFactory** is to handle a project where css and js is always output to the same location? one of the reasons i like the **ConfigManifestFileFactory** is that you can have multiple different locations, incredibly handy especially if the package is being dropped into a legacy project with a different set up.

**Comment by stevetemple** [comment]
What I have done in version 3.0.0 is remove the requirement to use any DI container, RevisionManifest should now be a singleton which creates it's own dependencies on creation. It's hardcoded to the ConfigManifestFileFactory so should work as before you just don't need to setup any DI for it. I have removed the Ninject module.

**Comment by stevetemple** [comment]
Thanks @ribsdigital for the effort put in, hopefully this'll make it simpler to use for you going forward.

**Comment by ribsdigital** [comment]
works a treat steve, i can remove the bindings in my autofac set up and everything still works as expected ;)

the only trick is that the package still pulls down ninject as a dependency?

image

**Pull request closed without merging**
